Feature/#67 위키 목록 페이지
codeitFE11-part3-team7/wikid pull request #113
Opened 2024-12-20 15:18 UTC by haksoo0918

## 이슈 번호

close #67 

## 변경 사항 요약

- 임의로 목록 개수를 5개로 정함

## 알림

- @crazyupinc-design 모바일에서 검색바 아이콘 깨지는 현상 확인 부탁드립니다.
- @solprime 모바일에서 GNB 레이아웃 확인 부탁드립니다.

## 테스트 결과

![image](https://github.com/user-attachments/assets/cfd58512-e881-467e-909d-4eb90815f2d8)
![image](https://github.com/user-attachments/assets/e4bb1a2c-142f-4054-9008-8438a624dc95)

2024-12-20 19:18 UTC, crazyupinc-design approved these changes
검색아이콘이 코딱지만큼 작아지네요 ㅜㅜ 확인했습니다.수정하겠습니다 
수고많으셨습니다!

2024-12-21 07:44 UTC, junghwa1996 requested changes
위에 모바일 텍스트 사이즈만 수정해주면 될 것 같습니다!
나머지는 너무 깔끔하게 작성 된 것 같아요! 고생하셨습니다 !!

2024-12-21 07:44 UTC, junghwa1996 commented on public/images/empty.png
해당 이미지는 컨벤션따라 img-empty로 저장하는게 어떨까용??

2024-12-21 07:44 UTC, junghwa1996 commented on pages/wikilist/index.tsx
> +            <p className="mt-4 text-16 text-gray-400">
모바일에서는 폰트 사이즈가 다릅니다! `mo:text-14`

2024-12-21 08:50 UTC, haksoo0918 commented on public/images/empty.png
모든 이미지에 img- 를 붙이나요?

2024-12-21 08:51 UTC, haksoo0918 commented on pages/wikilist/index.tsx
> +            <p className="mt-4 text-16 text-gray-400">
바로 확인해서 수정할께여.

2024-12-21 09:36 UTC, junghwa1996 commented on public/images/empty.png
음..........좀 고민되긴하네요 어차피 폴더로 구분되어있어서 딱히 안해도될것같기도 하네요 우선 냅두고 한번 팀원들이랑 얘기해보고 정하는게 좋을것같아요!

2024-12-21 11:51 UTC, junghwa1996 commented on pages/wikilist/index.tsx
> +            <p className="mt-4 text-16 text-gray-400">
여기 수정 된걸까요??

2024-12-21 12:59 UTC, haksoo0918 commented on pages/wikilist/index.tsx
> +            <p className="mt-4 text-16 text-gray-400">
네 수정했어요.

2024-12-21 14:59 UTC, junghwa1996 approved these changes

2024-12-22 01:30 UTC, merged