✨ 계정 설정 페이지 UI API
codeitFE11-part3-team7/wikid pull request #114
Opened 2024-12-20 18:38 UTC by crazyupinc-design

## 이슈 번호

close #61 

## 변경 사항 요약

- 계정설정페이지 UI구현, API연결했습니다 
- 인풋 너비 수정은 이슈생성해서 해당 이슈에서 수정하겠습니다.
- 비밀번호 변경 성공시 로그인 화면으로 이동합니다
- 위키 생성하기 성공시 내 위키 화면으로 이동합니다. (내위키는 한번만 생성이 가능하므로 안내문구나 수정이 가능한 기능이 추가되면 좋을 것 같습니다)

## Doc

_`컴포넌트 인 경우 props를 입력해주세요`_

| **Props** | **Type** | **Description** |
| --------- | -------- | --------------- |
| `  `      | `  `     | 내용 입력       |
| `  `      | `  `     | 내용 입력       |

_`hooks 및 utils 인 경우 input,output을 입력해주세요`_

|            | **prams** | **Type** | **Description** |
| ---------- | --------- | -------- | --------------- |
| **input**  | `  `      | `  `     | 내용 입력       |
| **output** | `  `      | `  `     | 내용 입력       |

## 테스트 결과
<img width="992" alt="iShot_2024-12-21_02 00 47" src="https://github.com/user-attachments/assets/ec3f45cf-c020-4e9c-b57c-f26317ba5c59" />

_`베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.`_
_`컴포넌트의 경우 스크린샷을 포함해주세요.`_

2024-12-20 18:52 UTC, crazyupinc-design commented
앗!!!  입력 폼 가운데 보더를 깜박했네요 ㅜㅜ 다시 추가 작업하겠습니다~~

2024-12-21 02:40 UTC, haksoo0918 approved these changes
오류 처리할게 많아서 고생하셨을것 같아요. 수고하셨습니다. 👍

2024-12-21 07:56 UTC, junghwa1996 requested changes
고생하셨습니다!

2024-12-21 07:56 UTC, junghwa1996 commented on pages/mypage/index.tsx
> +        setError(error.message);
오우 error 타입 검사까지 instanceof는 봤던것같긴한데 사용해본적이 없어서 처음 봅니다
instanceof 연산자 개념이 좀 어렵던데 쉽게 설명해주실 수 있을까요??

2024-12-21 07:56 UTC, junghwa1996 commented on pages/mypage/index.tsx
> +      await ProfileAPI.createProfile({
api/profileAPI 내 함수를 적절히 잘 이용하신 것 같습니다! 저도 참고하겠습니다!

2024-12-21 07:56 UTC, junghwa1996 commented on pages/mypage/index.tsx
> +          <div className="flex flex-col items-center gap-[8px]">
해당 스타일은 아래 :166 과 동일한 스타일을 가지고 있으니 변수로 빼서 호출하는건 어떨까요?

2024-12-21 07:56 UTC, junghwa1996 commented on pages/mypage/index.tsx
> +          <h2 className="mb-[40px] text-center text-24sb text-gray-500 mo:mb-[8px] ta:mb-[24px]">
부모 gap과 h2의 mb이 시안과 다른 것 같습니다 시안 상 간격은 64px인데 두 값을 합치면 실제 간격이 72px이 되니 수정이 필요할 것 같아요!

2024-12-21 10:40 UTC, crazyupinc-design commented on pages/mypage/index.tsx
> +          <div className="flex flex-col items-center gap-[8px]">
> 해당 스타일은 아래 :166 과 동일한 스타일을 가지고 있으니 변수로 빼서 호출하는건 어떨까요?

네 아래와 같이 변수로 분리했습니다 
  const inputSectionStyle = 'flex w-full flex-col items-center gap-[8px]';
  const inputContainerStyle = 'flex w-full flex-col gap-[8px]';

2024-12-21 10:40 UTC, crazyupinc-design commented on pages/mypage/index.tsx
> +          <h2 className="mb-[40px] text-center text-24sb text-gray-500 mo:mb-[8px] ta:mb-[24px]">
> 부모 gap과 h2의 mb이 시안과 다른 것 같습니다 시안 상 간격은 64px인데 두 값을 합치면 실제 간격이 72px이 되니 수정이 필요할 것 같아요!

넵 mb32 + gap32 = 64px로 수정했습니다

2024-12-21 10:40 UTC, crazyupinc-design commented on pages/mypage/index.tsx
> +        setError(error.message);
> 오우 error 타입 검사까지 instanceof는 봤던것같긴한데 사용해본적이 없어서 처음 봅니다 instanceof 연산자 개념이 좀 어렵던데 쉽게 설명해주실 수 있을까요??

@junghwa1996  instanceof는 물건의 출처를 확인하는 도구라고 하네요.
왼쪽의 객체가 오른쪽 클래스의 자손인지".
=> error객체가 Error클래스의 자손이면 
error.message 속성을 에러 메시지로 설정하시요~

**객체가 특정 클래스나 생성자 함수에서 생성되었는지 확인해서, 안전하게 코드를 처리하거나 특정 동작을 수행하기 위해서** 사용한다고 합니다. 
제가 적은 코드처럼 에러 처리에서 특정 에러만 다루는 경우로도 많이 사용한다고 하네요.

2024-12-21 11:52 UTC, junghwa1996 commented on pages/mypage/index.tsx
> +        setError(error.message);
아 이해했습니다 설명 감사합니다!

2024-12-21 11:56 UTC, junghwa1996 approved these changes

2024-12-21 13:10 UTC, merged