Feature/#62 메인랜딩페이지
codeitFE11-part3-team7/wikid pull request #130
Opened 2024-12-22 10:57 UTC by crazyupinc-design

## 이슈 번호

close #62 

## 변경 사항 요약

- 랜딩페이지 애니메이션 효과 제외하고 구현했습니다. 
- 아...반응형 작업이 이렇게 힘들줄이야..ㅜㅜ 
- 확인부탁드립니다 

## Doc

_`컴포넌트 인 경우 props를 입력해주세요`_

| **Props** | **Type** | **Description** |
| --------- | -------- | --------------- |
| `  `      | `  `     | 내용 입력       |
| `  `      | `  `     | 내용 입력       |

_`hooks 및 utils 인 경우 input,output을 입력해주세요`_

|            | **prams** | **Type** | **Description** |
| ---------- | --------- | -------- | --------------- |
| **input**  | `  `      | `  `     | 내용 입력       |
| **output** | `  `      | `  `     | 내용 입력       |

## 테스트 결과

_`베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.`_
_`컴포넌트의 경우 스크린샷을 포함해주세요.`_

2024-12-22 12:44 UTC, haksoo0918 approved these changes
반응형 작업하시기 힘드셨을 텐데 수고하셨습니다. 👍

2024-12-22 12:44 UTC, haksoo0918 commented on components/Landing/Footer.tsx
> +        Copyright ⓒ Wikied. All Rights Reserved <br />
요거는 팁인데, ⓒ 요 특수기호는 `&copy;` 로 사용하시는걸 추천합니다.

2024-12-22 12:44 UTC, haksoo0918 commented on components/Landing/Footer.tsx
> +본 약관은 ㈜코드잇이 제공하는 Codeit 서비스를 이용함에 있어 이용자의 권리, 의무 및 책임사항을 규정함을 목적으로 합니다.
이런 긴 텍스트는 따로 빼는 것도 좋을것 같습니다.

2024-12-22 12:44 UTC, haksoo0918 commented on components/Landing/FinalSection.tsx
> +};
요걸 css 파일로 뺀 것이 module css 방법입니다.

2024-12-22 12:51 UTC, junghwa1996 requested changes

2024-12-22 12:51 UTC, junghwa1996 commented on components/Landing/HeroSection.tsx
> +                </h2>
여기 line-height가 포함이 안된것같아요 line-height 추가해주시고 두 간격이 pc에서는 20px이니 맞춰주세요!

2024-12-22 12:51 UTC, junghwa1996 commented on components/Landing/FinalSection.tsx
> +          href="/signup"
로그인이 되어있지 않을때는 signup이 아닌 login으로 이동입니다!

2024-12-22 12:51 UTC, junghwa1996 commented on components/Landing/HeroSection.tsx
> +          <Button href="/signup" variant="dark" size="large">
여기도 로그인이 안되어있을 경우에는 login으로 이동되어야합니다!

2024-12-22 14:16 UTC, crazyupinc-design commented on components/Landing/Footer.tsx
> +        Copyright ⓒ Wikied. All Rights Reserved <br />
> 요거는 팁인데, ⓒ 요 특수기호는 `&copy;` 로 사용하시는걸 추천합니다.

오호!! 감사합니다. 수정작업시 반영하겠습니다

2024-12-22 14:18 UTC, crazyupinc-design commented on components/Landing/FinalSection.tsx
> +};
> 요걸 css 파일로 뺀 것이 module css 방법입니다.

확장프로그램으로 테일윈드 잘 쓰는법 좀더 방법을 익혀보겠습니다.

2024-12-24 10:04 UTC, junghwa1996 commented
#174 에 이어서 작업함

2024-12-24 10:04 UTC, closed without merging