Feature/#162 프로필 컴포넌트 인풋 수정
codeitFE11-part3-team7/wikid pull request #163
Opened 2024-12-23 13:52 UTC by horororok

## 이슈 번호

close #162 

## 변경 사항 요약

- 프로필 컴포넌트 이미지 인풋 수정

## Doc

## 테스트 결과

2024-12-23 14:34 UTC, junghwa1996 requested changes
![스크린샷 2024-12-23 오후 11 31 21](https://github.com/user-attachments/assets/92e6d61b-faef-4259-b264-378102996991)
![스크린샷 2024-12-23 오후 11 31 28](https://github.com/user-attachments/assets/8fa94427-52bb-4098-940d-19c877147b36)

여기 스타일이 좀 많이 이상해졋어요ㅠㅠ

2024-12-23 14:34 UTC, junghwa1996 commented on components/UserProfile.tsx
>  interface ProfileData {
여기타입은 별도로 분리해서 @solprime 예도님 페이지에서 같이 쓰면 좋을것같습니다~

2024-12-23 14:34 UTC, junghwa1996 commented on components/UserProfile.tsx
> +                ) : (
오 로딩스피너 만드셨군요! 이거 컴포넌트로 만들어주시면 다른분들도 쓰기 편할것같아요 👍🏻

2024-12-23 14:58 UTC, solprime approved these changes
고생하셨습니다!

2024-12-24 10:13 UTC, junghwa1996 commented
@horororok 디코보시고 에러 수정 부탁드려요!

2024-12-24 10:52 UTC, junghwa1996 approved these changes

2024-12-24 10:56 UTC, junghwa1996 commented
빌드 테스트 하느라 머지가 불가합니다 @solprime 예도님이 해당 브랜치에서 이어서 추가작업 해주세요

2024-12-24 11:26 UTC, merged