Feature/#246 qa   메인
codeitFE11-part3-team7/wikid pull request #248
Opened 2024-12-27 16:00 UTC by crazyupinc-design

## 이슈 번호

close #246 

## 변경 사항 요약

 파일형식 : 로고나 아이콘은 svg, 투명이 필요하면 png, 나머지 사진등은 jpg 로 바꿔주세요.
=> 교체했습니다. 아이폰으로 확인시 이미지 깨지는 현상없는것 확인했습니다. 

 메인 경고문: 메인에서 위키만들기(지금시작하기, 회원가입,로그인)로 넘어가면 콘솔에 경고문 뜹니다
=> 비밀번호 관련 입력 필드에서 발생하는 에러라고 합니다. 저는 지금 재현되지 않고 있습니다. 혹시 수정이 된건가 싶은데요, 다시한번 확인부탁드립니다 

 화면 전환: 위키가 있을때 버튼 클릭시 내 위키 화면으로 이동
=> 이동됨 확인했습니다 

 모바일 이미지 깨짐: [mo-아이폰15] 메인에 다크모드 bg 중간에 하얗게 됨
=> 학수님께서 배경 언덕 수정하시면 재현되지 않을 것 같습니다. 

## Doc

_`컴포넌트 인 경우 props를 입력해주세요`_

| **Props** | **Type** | **Description** |
| --------- | -------- | --------------- |
| `  `      | `  `     | 내용 입력       |
| `  `      | `  `     | 내용 입력       |

_`hooks 및 utils 인 경우 input,output을 입력해주세요`_

|            | **prams** | **Type** | **Description** |
| ---------- | --------- | -------- | --------------- |
| **input**  | `  `      | `  `     | 내용 입력       |
| **output** | `  `      | `  `     | 내용 입력       |

## 테스트 결과

_`베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.`_
_`컴포넌트의 경우 스크린샷을 포함해주세요.`_

2024-12-27 16:28 UTC, junghwa1996 requested changes

2024-12-27 16:28 UTC, junghwa1996 commented on public/images/empty.png
이 이미지는 왜 png로 바꾸신거죠?? 메인에서는 사용되지않는 이미지 인데요 ㅠㅠ 이건 empty 컴포넌트에서 사용되는 svg입니다!

2024-12-27 16:29 UTC, crazyupinc-design commented on public/images/empty.png
> 이 이미지는 왜 png로 바꾸신거죠?? 메인에서는 사용되지않는 이미지 인데요 ㅠㅠ 이건 empty 컴포넌트에서 사용되는 svg입니다!

바꾸는작업을 다 제가 담당하는줄 알았어요 ㅜㅜ 다시 원복하겠습니다

2024-12-27 16:50 UTC, crazyupinc-design commented on public/images/empty.png
> 이 이미지는 왜 png로 바꾸신거죠?? 메인에서는 사용되지않는 이미지 인데요 ㅠㅠ 이건 empty 컴포넌트에서 사용되는 svg입니다!

파일 원복했습니다

2024-12-27 16:51 UTC, junghwa1996 approved these changes

2024-12-28 01:56 UTC, haksoo0918 approved these changes
수고하셨습니다. 👍

2024-12-28 02:56 UTC, merged