Feature/#265 추가기능 알림 기능
codeitFE11-part3-team7/wikid pull request #273
Opened 2024-12-28 12:31 UTC by solprime

## 이슈 번호

close #265 

## 변경 사항 요약

- 알림 기능 구현했습니다.
- 다른 사람이 내 위키를 수정했을 때만 알림이 옵니다. (내 위키를 내가 수정하면 알림x)
- 알림을 누르면 내 위키로 이동 후 알림은 삭제됩니다.

- 꼼꼼하게 체크 부탁드립니다!

## 테스트 결과

**비어있을 경우**
![image](https://github.com/user-attachments/assets/bbda9527-056f-4508-845f-5ae8689c93e5)

**알림 있을 때**

![image](https://github.com/user-attachments/assets/ec93140d-d389-4573-be90-e7c4a344057c)

**모바일 환경**
![image](https://github.com/user-attachments/assets/d6edc52f-3bc9-4123-848f-e574f4e56bd8)

2024-12-28 13:05 UTC, junghwa1996 requested changes
우선 확인된게  이정도라 좀 더 확인해보고 추가 리뷰 남기겠습니다!

2024-12-28 13:05 UTC, junghwaYang commented on components/Headers/Alarm.tsx
> +      <button onClick={handleAlarmOpen}>
html 구조상 button 태그 안에 button 태그를 중복으로 사용이 불가합니다!
`In HTML, <button> cannot be a descendant of <button>.
This will cause a hydration error.` 에러 발생합니다

해당 부분
```suggestion
<div role="button" tabIndex={0} onClick={handleAlarmOpen}>
```
로 변경하면 좋을 듯 해요!
그리고 알람 클릭 후 알람 모달이 떳을때, 종 모양 한번더 클릭하면 모달이 닫히는걸 예상했는데 닫히지않고 다시 열리네요! 해당 액션 개선되면 좋을것같습니다!

2024-12-28 13:05 UTC, junghwaYang commented on components/Headers/Login.tsx
해당 모달에 지금 피그마 확인해보니
로그인 상태에서는 
`마이페이지, 로그아웃` 만 뜨는게 아닌 `마이페이지, 내 위키, 로그아웃` 이 떠있네요
그리고 `로그아웃` 부분은 `#8F95B2` 컬러 입니다!

추가로 프로필 눌렀을때 뜨는 드롭다운은 border가 없습니다 border 제거하셔야할 것 같습니다
스타일 수정해주세요!

2024-12-28 14:14 UTC, solprime commented on components/Headers/Alarm.tsx
> +      <button onClick={handleAlarmOpen}>
수정했습니다 확인 부탁드립니다!

2024-12-28 14:17 UTC, junghwa1996 commented on components/Headers/Alarm.tsx
> +      <button onClick={handleAlarmOpen}>
디코 자유대화방 봐주세요 ㅠㅠ

2024-12-28 15:33 UTC, junghwa1996 requested changes
`Menu.tsx`에 있는 `const fadeIn = 'pc:animate-pcFadeIn tamo:animate-tamoFadeIn';` 해당 애니메이션 globals.css에 
```css
.downFadein{
  @apply pc:animate-pcFadeIn tamo:animate-tamoFadeIn
}
```
이렇게 추가하셔서 Menu에도 downFadein 추가하시고, 알람에서도 해당 인터럭션 추가되면 좋을것같아요~

2024-12-28 15:33 UTC, junghwa1996 commented on components/Notification/NorificationBox.tsx
> +    <div className="absolute right-0 z-20 flex max-h-[293px] w-[368px] flex-col gap-[16px] rounded-custom bg-gray-200 px-[24px] py-[20px] mo:top-[30px] mo:w-[250px]">
프로필 눌렀을때 margin-top과 동일했으면 좋을것같아요 너무 종 아이콘과 딱 붙어있어요! 프로필 드롭다운 margin-top: 8px
그리고 py,px 값이 바뀐것같아요! 위아래 24px 좌우 20px 입니당
dropshadow도 들어가있어야할것같아용 dark: 도 잊지말고 넣어주세요!

2024-12-28 15:33 UTC, junghwa1996 commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
여기는 계속 빨간불만 들어오나요? 시안 기획의도상 오래된 알림이 빨간색으로 표기되고 가장 최근 알림만 초록불로 표기가 되는것같아요~
의미상 그렇게 컬러값을 지정하는게 맞을것같습니다!

2024-12-28 15:34 UTC, solprime commented on components/Headers/Login.tsx
커밋이 꼬여서 지금올립니다!

2024-12-28 15:42 UTC, solprime commented on components/Notification/NorificationBox.tsx
> +    <div className="absolute right-0 z-20 flex max-h-[293px] w-[368px] flex-col gap-[16px] rounded-custom bg-gray-200 px-[24px] py-[20px] mo:top-[30px] mo:w-[250px]">
다크모드에선 어떻게 넣으면 되는건가요

2024-12-28 16:08 UTC, solprime commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
수정했습니다!

2024-12-28 16:20 UTC, junghwa1996 commented
@solprime 지금 계속 `In HTML, <button> cannot be a descendant of <button>.` 에러가 떠서 확인해보니까 `NotificationContents.tsx` 안에도 버튼태그가 들어가있어서 에러가 발생하는것같습니다.
개발자도구 확인하셔서 button안에 button이 들어가는 일이 없도록 수정해주셔야할것같습니다

2024-12-28 16:22 UTC, junghwa1996 commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
생각해보니 여기는 오래된 알람의 시간 기준을 정하지않았네요..ㅎㅎ
하루가 지나면 오래된 알람으로 빨간색 불이 들어온다는건 확인했습니다!
가장 최상위에 떠있는거만 초록불이고 그 아래는 모두 빨간불이 들어오게하는건 어려울까요? index 이용해서 index 0번에만 초록불이 들어오게 하면 구현이 될것같긴합니다만 의견주시죵!

2024-12-28 16:27 UTC, solprime commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
가능하긴한데 가장 최근 알림만 파란불이 뜨는건 별 의미가 없을 것 같아서 저렇게 해뒀습니다

2024-12-28 16:29 UTC, junghwa1996 commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
우선 알겠습니다! 뭔가 시연 영상찍을때 저 빨간불도 있다는걸 알려주려면 하루단위가 아닌 시간이나 분으로 설정하면 더 좋을듯합니다...!! 어떠신가요!

2024-12-28 16:30 UTC, solprime commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
6시간정돈 어떠세요

2024-12-28 16:34 UTC, junghwa1996 commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
넹 그럼 6시간으로 하시죵!

2024-12-28 16:43 UTC, solprime commented on components/Notification/NotificationContents.tsx
> +          <div className="size-[5px] rounded-full bg-red-100"></div>
수정했습니다!

2024-12-28 16:44 UTC, junghwa1996 approved these changes

2024-12-30 03:42 UTC, haksoo0918 approved these changes
이미지 보니 이뿌게 잘 나온거 같아요. 😄 
수고하셨습니다. 👍

2024-12-30 03:42 UTC, haksoo0918 commented on components/Notification/NotificationContents.tsx
> +  }
utils 폴더에 dateConversion 있는데 중복되지는 않나요?

2024-12-30 04:42 UTC, solprime commented on components/Notification/NotificationContents.tsx
> +  }
dateConversion 함수는 하루 지나면 날짜가 나오고, 제가 구현한건 며칠이 지났는지 나와서 조금 다릅니다. 아무래도 알림이다 보니 날짜보단 며칠 전 알림인지 나타내주는게 더 나을 것 같아서요

2024-12-30 07:22 UTC, merged