Feature/#19 인풋필드 컴포넌트
codeitFE11-part3-team7/wikid pull request #30
Opened 2024-12-15 07:58 UTC by crazyupinc-design

### 이슈 번호

close #19

### 변경 사항 요약

인풋필드 Props Type
```typescript
interface InputFieldProps {
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  type?: 'text' | 'email' | 'password' | 'name' | 'passwordConfirm';
  placeholder?: string;
  label?: string;
  compareValue?: string;
}
```

사용예시
```typescript
<InputField
        label="이메일"
        type="email"
        value={email}
        onChange={handleEmailChange}
        placeholder="이메일을 입력해 주세요"
      />
```

signup페이지는 미완성이므로 리뷰하지 않으셔도 됩니다. 

### 테스트 결과

<img width="504" alt="image" src="https://github.com/user-attachments/assets/133ce768-32cd-4bd9-9dd9-5c49fae3d6b5" />

2024-12-15 08:57 UTC, junghwa1996 requested changes
생일 input에서는 달력이 노출되게끔 사용하신다하셨는데 해당 부분에 대한 코드는 없는것같아요!

2024-12-15 08:57 UTC, junghwa1996 commented on components/Input.tsx
> +  };
해당 input 유효성 검사는 커스텀 hooks로 빼서 쓰는게 좋을것같아요!
그리고 회원가입 로그인 이외에도 위키 참여 인증 모달 답변에도 해당 답변에 대한 유효성 검사가 필요할것같아서
유효성 검사를 hooks로 빼고 input 컴포넌트 내부에서 검사를 하는게 아닌 외부에서 하도록 하는게 좋을것같습니다!

2024-12-15 08:57 UTC, junghwa1996 commented on components/Input.tsx
> +const InputField: React.FC<InputFieldProps> = ({
컴포넌트 함수는 화살표 함수가 아닌 function 함수를 사용해주세요!

2024-12-15 08:57 UTC, junghwa1996 commented on components/Input.tsx
> +    container: 'mb-[24px] flex flex-col gap-[10px]',
라벨 스타일의 경우 세로 형태 뿐만 아닌 가로 형태도 있으니, 가로인지 세로인지에 대한 스타일 타입을 props로 받는게 좋을 것 같습니다!

2024-12-15 08:59 UTC, junghwa1996 commented on pages/signup/index.tsx
PR은 하나의 작업만 올려주세용~

2024-12-15 09:06 UTC, junghwa1996 commented
dev 최신사항 변경해놨고 merge 컴플릿 나는거 해결해서 푸시했어요~
그리고 다음부터는 하나의 브랜치의 한개의 작업만 부탁드려요!
> 페이지에 테스트 하고 브랜치를 옮겨서 작업 할 경우 `git stash` 하고 브랜츠 옮기신 후에 올바른 브랜치에서 커밋올리시면 됩니당

2024-12-16 04:23 UTC, haksoo0918 reviewed
~~이 컴포넌트가 유지되는 건가요? 제가 정확히는 잘 몰라서...~~
제가 프로필 필드하고 헷갈린거 같아요. 💦 
다시 리뷰 필요하시면 리뷰어 제 아이디 옆에 're-request review' 버튼 눌러주세요. 😄

2024-12-16 04:23 UTC, haksoo0918 commented on components/Input.tsx
> +        }
중첩 삼항연산자는 지양하는게 좋아 보입니다.

2024-12-16 06:19 UTC, junghwa1996 commented on components/Input.tsx
> +  };
훅 분리하신거 확인했습니다

2024-12-16 06:19 UTC, junghwa1996 commented on components/Input.tsx
> +const InputField: React.FC<InputFieldProps> = ({
수정 확인헀습니다

2024-12-16 06:20 UTC, junghwa1996 commented on components/Input.tsx
> +    container: 'mb-[24px] flex flex-col gap-[10px]',
@crazyupinc-design 이건 아직 진행중이신걸까요?

2024-12-16 06:34 UTC, crazyupinc-design commented on components/Input.tsx
> +const InputField: React.FC<InputFieldProps> = ({
네 수정하겠습니다

2024-12-16 06:34 UTC, crazyupinc-design commented on components/Input.tsx
> +    container: 'mb-[24px] flex flex-col gap-[10px]',
프로필 인풋은 따로 만들려고 해요

2024-12-16 06:34 UTC, crazyupinc-design commented on components/Input.tsx
> +  };
input 유효성 검사 커스텀 hooks로 분리했습니다. 
해당 파일 useValidation.tsx 확인부탁드립니다

2024-12-16 06:34 UTC, crazyupinc-design commented on components/Input.tsx
> +        }
> 중첩 삼항연산자는 지양하는게 좋아 보입니다.
넵 조건문 함수로 대체했습니다 확인부탁드립니다

2024-12-16 06:34 UTC, crazyupinc-design commented on components/Input.tsx
> +    container: 'mb-[24px] flex flex-col gap-[10px]',
> @crazyupinc-design 이건 아직 진행중이신걸까요?

수정해서 push했습니다. 확인부탁드립니다 
사용예시 본문내용 변경하겠습니다

2024-12-16 06:37 UTC, junghwa1996 commented on components/Input.tsx
> +    container: 'mb-[24px] flex flex-col gap-[10px]',
확인했습니다 수고하셨습니다!

2024-12-16 06:38 UTC, junghwa1996 commented
> 생일 input에서는 달력이 노출되게끔 사용하신다하셨는데 해당 부분에 대한 코드는 없는것같아요!

이거도 같이 작업끝난거죠?? 커밋에 같이 올라와있더라구요!

2024-12-16 06:38 UTC, crazyupinc-design commented
> 생일 input에서는 달력이 노출되게끔 사용하신다하셨는데 해당 부분에 대한 코드는 없는것같아요!

생일 레이블일때 인풋창 클릭시 데이픽커(달력)나오도록 구현했습니다 
데이픽커는 추후 추가개발때 스타일 수정하겠습니다

2024-12-16 06:48 UTC, crazyupinc-design commented
> > 생일 input에서는 달력이 노출되게끔 사용하신다하셨는데 해당 부분에 대한 코드는 없는것같아요!
> 
> 이거도 같이 작업끝난거죠?? 커밋에 같이 올라와있더라구요!

생일 레이블일때 인풋창 클릭시 데이픽커(달력)나오도록 구현했습니다
데이픽커는 추후 추가개발때 스타일 수정하겠습니다

2024-12-16 07:37 UTC, junghwa1996 approved these changes

2024-12-16 08:28 UTC, haksoo0918 approved these changes
수고하셨습니다. 👍

2024-12-16 08:28 UTC, haksoo0918 commented on components/Input.tsx
> +          </p>
p 태그로 감싼 이유가 궁금합니다.

2024-12-16 08:55 UTC, crazyupinc-design commented on components/Input.tsx
> +          </p>
> p 태그로 감싼 이유가 궁금합니다.

p태그로 해당 라이브러리 이름을 임시로 적어놓고 수정하는것을 깜박했네요.
수정하겠습니다

2024-12-16 09:59 UTC, merged