✨ 검색창 컴포넌트 제작
codeitFE11-part3-team7/wikid pull request #33
Opened 2024-12-15 11:15 UTC by crazyupinc-design

### 이슈 번호

close #31

### 변경 사항 요약

SearchInput 컴포넌트
```
 - 크기별 구현 (large:위키목록페이지), medium: 자유게시판페이지) 
 - 기본 Placeholder 제공: large는 "이름으로 위키 검색", medium은 "제목을 검색해 주세요."
 - Props: size, value, onSubmit, placeholder
```

사용예시 
```
 <SearchInput
        size="large"
        value="기본 검색어"
        onSubmit={handleSearch}
      />
```

### 테스트 결과

<img width="967" alt="image" src="https://github.com/user-attachments/assets/72372efc-ae36-4e13-9b19-5e6b63f381b2" />

2024-12-15 12:39 UTC, junghwaYang requested changes

2024-12-15 12:39 UTC, junghwaYang commented on components/SearchInput.tsx
> +        </div>
해당 아이콘을 따로 absolute로 띄우신 이유가 있을까욥??
저는 form에 padding을 주고 영역 차지하게 하고 input과 간격을 둘 것 같아서요!

2024-12-15 12:39 UTC, junghwaYang commented on components/SearchInput.tsx
> +    size === 'large' ? '이름으로 위키 검색' : '제목을 검색해 주세요.';
size props로 placeholder를 정의해준다는게 의미상 맞지 않는것같아요!
아마 해당 searchInput이 사용되는 페이지에 따라 다르게 보이게끔 하고싶으셔서 지정하신것같은데
size props로 정하기보다는 아예 placeholder를 유저(다른개발자)가 지정할 수 있게 하는건 어떨까요?

2024-12-15 12:39 UTC, junghwaYang commented on components/SearchInput.tsx
> +  const [inputValue, setInputValue] = useState(value);
value는 외부에서 받는게 좋을것같습니다!
현재 컴포넌트에서 value state를 처리하게 될 경우 외부에서 해당 value를 이용해 활용하기가 어려울 것 같아요

2024-12-15 14:42 UTC, crazyupinc-design commented on components/SearchInput.tsx
> +        </div>
인풋필드안에 아이콘 배치는 항상 absolute로 작업했던 터라 (익숙해서 선택한 방식입니다^^) 
아이콘 input을 수평 정렬로 변경했습니다

2024-12-15 14:44 UTC, crazyupinc-design commented on components/SearchInput.tsx
> +    size === 'large' ? '이름으로 위키 검색' : '제목을 검색해 주세요.';
유저가 지정할 수 있도록 코드 수정했습니다 
본문의 사용예시 변경했습니다

2024-12-15 14:46 UTC, crazyupinc-design commented on components/SearchInput.tsx
> +  const [inputValue, setInputValue] = useState(value);
내부 상태 관리 제거했습니다 
다시한번 확인부탁드립니다

2024-12-16 02:42 UTC, haksoo0918 approved these changes
코드가 깔끔해서 보기 좋습니다. 👍

2024-12-16 02:42 UTC, haksoo0918 commented on components/SearchInput.tsx
> +      />
제가 추천하는 방향은 이미지를 라벨로 감싸고 처리하는 방식입니다.
```html
<label htmlFor="searchInput"><img src="..." alt="검색" /></label>
<input id="searchInput" ... />
```
이렇게 하면 이미지를 클릭해도 인풋으로 포커스가 이동합니다.
이미지 태그의 alt속성도 '검색 아이콘' 보다는 인풋의 라벨 역할로 '검색' 으로 하시면 좋을것 같습니다.

2024-12-16 03:46 UTC, junghwa1996 approved these changes

2024-12-16 03:48 UTC, junghwa1996 commented on components/SearchInput.tsx
> +      />
@crazyupinc-design 이 방식이 더 좋을것같네요 !!

2024-12-16 07:21 UTC, crazyupinc-design commented on components/SearchInput.tsx
> +      />
> @crazyupinc-design 이 방식이 더 좋을것같네요 !!

추천해주신 코드로 수정했습니다 확인부탁드립니다

2024-12-16 07:29 UTC, crazyupinc-design commented on components/SearchInput.tsx
> +      />
> 제가 추천하는 방향은 이미지를 라벨로 감싸고 처리하는 방식입니다.
> 
> ```
> <label htmlFor="searchInput"><img src="..." alt="검색" /></label>
> <input id="searchInput" ... />
> ```
> 
> 이렇게 하면 이미지를 클릭해도 인풋으로 포커스가 이동합니다. 이미지 태그의 alt속성도 '검색 아이콘' 보다는 인풋의 라벨 역할로 '검색' 으로 하시면 좋을것 같습니다.

추천해주신 코드로 수정했습니다 확인부탁드립니다

2024-12-16 09:53 UTC, merged