Feature/#22 접속 끊김 모달 컴포넌트
codeitFE11-part3-team7/wikid pull request #40
Opened 2024-12-16 09:35 UTC by horororok

### 이슈 번호

close #22

### 변경 사항 요약

접속 끊김 모달, 저장하지 않고 나가기 모달 구현
두 모달의 경우 확인 버튼 클릭 시 페이지 초기화 필요 -> 기능은 페이지 작업 진행시 함께 작업 예정

### 테스트 결과

베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.

![image](https://github.com/user-attachments/assets/e8ad335d-95df-4918-9a3c-1759006aa5ea)
![image](https://github.com/user-attachments/assets/8f53517d-474f-487a-9e40-fd651b3686ff)

2024-12-16 10:46 UTC, junghwa1996 requested changes
이전 #39 PR 이후로 추가 수정하신건가요? (Modal.tsx, WikiQuizModal.tsx, ImageUploadModal.tsx)
바뀐 내역에 포함이 되어있네요
이전 PR과 수정사항은 동일한것같습니다 확인해보시고 수정해주세요!

2024-12-16 10:46 UTC, junghwaYang commented on components/DisconnectionModal.tsx
> +    </Modal>
여기도 #39 PR 리뷰 남겨드린것처럼 컨텐츠만 분리해서 작성하는게 좋을듯합니다!

2024-12-16 10:46 UTC, junghwaYang commented on components/DisconnectionModal.tsx
> +          </button>
여긴 공통컴포넌트로 수정해주세요!

2024-12-16 10:46 UTC, junghwaYang commented on components/UnsavedChangesModal.tsx
> +    </Modal>
여기도 동일하게 컨텐츠에 대한 JSX를 리턴하게끔해주세용

2024-12-16 10:49 UTC, junghwaYang commented
여기도 이슈 넘버 잘못들어가서 제가 수정해두었습니다~

2024-12-17 07:42 UTC, haksoo0918 approved these changes
주석도 너무 이뿌게 달아주시고, 이미지 모달에 드래그 까지 넣어주시고 수고하셨습니다. 👍

2024-12-17 07:42 UTC, haksoo0918 commented on components/ImageUploadModal.tsx
> +  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
타입이 string 이면 기본값으로 null 대신 빈값('')을 사용하셔도 될 것 같은데 null 값을 사용하신 이유가 있을까요?

2024-12-17 07:42 UTC, haksoo0918 commented on components/ImageUploadModal.tsx
> +                </svg>
이 svg 도 return 안쪽이 아닌 함수 바깥이나 별도 아이콘 파일로 public 폴더에 두는것이 좋아 보입니다.

2024-12-18 04:17 UTC, merged