Feature/#36 gnb 컴포넌트
codeitFE11-part3-team7/wikid pull request #42
Opened 2024-12-16 11:51 UTC by solprime

### 이슈 번호

close #36 

### 변경 사항 요약

- 외부 클릭 시 메뉴팝업이 닫히는 로직은 커스텀 훅으로 따로 제작했습니다.
- 로그인 관련 부분과 로그인 시 프로필 이미지 부분은 아직 미완성입니다. 이 부분은 로그인 및 프로필 컴포넌트가 완성되면 추후에 다시 제작하겠습니다.

### 테스트 결과

**로그인 전**
![image](https://github.com/user-attachments/assets/fc4c229b-0be3-4c44-a5ee-85f6dee4d22f)

**로그인 전(모바일)**
![image](https://github.com/user-attachments/assets/90c3a9ff-4821-415e-8dae-90d4a3418641)

**로그인 후**
![image](https://github.com/user-attachments/assets/243a35ab-4847-4dc2-9fd8-0a1492481f6d)

**로그인 후(모바일)**
![image](https://github.com/user-attachments/assets/d4af3ce5-01e3-4f71-9941-d3df95719998)

2024-12-16 12:17 UTC, junghwa1996 requested changes
여러 기능이 복합적으로 들어가있다보니 고민이 많으셨을것같아요
제가 남겨드린 리뷰 읽어보시고 조금 더 유지보수하기 편한 방향으로 수정되면 더 좋을것같아요!
기능적인 부분에는 흠잡을것없이 완벽합니당 고생많으셨어요 !

2024-12-16 12:17 UTC, junghwa1996 commented on hooks/useOutsideClick.tsx
오 이거는 태훈님 모달에서도 활용해볼 수 있는 공통 훅 인것같네요! @horororok 참고하셔서 모달 bg close에서 사용해보면 좋을듯합니다!

2024-12-16 12:17 UTC, junghwa1996 commented on components/GNB.tsx
> +
여기는 임의로 나중에 수정될 부분이니 Anchors 이용해서 `// TODO` 이렇게 하면 나중에 까먹지않고 한눈에 알아볼 수 있어서 좀 더 편할 것 같습니다!!

2024-12-16 12:17 UTC, junghwa1996 commented on components/GNB.tsx
해당 컴포넌트에 너무 많은 기능을 담고있는것같아요~
차라리 파일을
```
components/
  Headers/
    Headers.tsx
    Gnb.tsx
    Menu.tsx
    Alert.tsx
    Login.tsx
```
이런식으로 컴포넌트 분리를 해보는건 어떨까요??
단일 책임 원칙을 생각해보면서 작업하시면 좋을 것 같아요!

하나의 컴포넌트에 많은 기능이 들어가있다보니 가독성도 떨어지고 유지보수하기가 어려울 것 같습니다 ㅠㅠ!

2024-12-16 14:51 UTC, solprime commented on components/GNB.tsx
최대한 분리해봤습니다..!

2024-12-16 14:51 UTC, solprime commented on components/GNB.tsx
> +
앞으로 참고하겠습니다!

2024-12-16 15:41 UTC, junghwa1996 requested changes
`components/GNB` 보다는
`components/Headers` 가 더 이해하기 쉬울 것 같아요~

2024-12-16 15:41 UTC, junghwa1996 commented on components/GNB/Header.tsx
> +    <div className="flex items-center gap-10">
header 컴포넌트 의미에 맞게 올바른 시멘틱 태그 사용해주세요!
```
<header></header>
```

2024-12-16 15:41 UTC, junghwa1996 commented on components/GNB/Header.tsx
> +export default function Header() {
시멘틱 태그와 동일한 컴포넌트 명은 에러를 발생 시킬 수 있어요!
`Headers` 로 변경해주세요! => 파일명도 동일

2024-12-16 15:41 UTC, junghwa1996 commented on components/GNB/Header.tsx
> +      </button>
`button`태그 보다는 `Link` 태그를 쓰는게 더 적절할 것 같아요

그리고 headers 컴포넌트는
```javascript
<header>
  <Link href='/'>
    <img src="/logo.svg" alt="위키드 로고" />
  </Link>
  <Gnb />
    {/* 로그인 여부에 따라 조건부로 노출 */}
    {isLoggedIn ? (
      <div className="flex items-center gap-5">
        <Alarm />
        <ProfileIcon isMobile={isMobile} logout={handleLogout} />
      </div>
    ) : (
      <Login login={handleLogin} isMobile={isMobile} />
    )}
</header>
```
이렇게 넣는게 더 좋을것같습니다..!!!

2024-12-16 15:41 UTC, junghwa1996 commented on components/GNB/ProfileIcon.tsx
> +        )}
여기 로직은 이미 Login 컴포넌트에 있으니 제거 하셔도 될것같습니다!
해당 컴포넌트에 들어가는 options나 handleProfileMenu 함수도 지워주셔도 될 것 같습니다!

2024-12-16 15:41 UTC, junghwa1996 commented on components/GNB/GNB.tsx
> +    </div>
여기는 컴포넌트 의미에 맞게 
```javascript
<div className="z-100 fixed left-0 top-0 flex h-20 w-full items-center justify-between bg-background px-20 py-5 shadow-custom">
  <Link href='/wikilist'>
    위키목록
  </Link>
  <Link href='/boards'>
    자유게시판
  </Link>
</div>
```
딱 이렇게만 들어가는게 좋을듯 해요 호출은 Header.tsx서 하는걸로!

2024-12-16 15:41 UTC, junghwa1996 commented on pages/test/GNB/index.tsx
여기 호출도 GNB가 아닌 모든걸 감싸고있는 headers 컴포넌트를 호출하는걸로 해보셔요!

2024-12-16 15:41 UTC, junghwa1996 commented on components/GNB.tsx
추가 리뷰 남겼습니당

2024-12-16 15:43 UTC, junghwa1996 commented on components/GNB.tsx
> +
Anchors 확장 플러그인은
https://abalone-vinyl-fea.notion.site/14c6be7a37cb8056b967d85d036df14b?pvs=4
저희 노션에 보면 '주석' 부분 참고하시는게 좋을 것 같습니다!
그리고 TODO 로 요청드린 이유가 나중에 작업해야하는 부분이기에 ANCHOR(코멘트) 의 의미보다는 TODO(할 일) 이 더 적합할것같아요! 
그리고 가로 옆 주석보다는 
```javascript
// TODO 임시 로그인 상태(추후 업데이트예정)
  const [isLoggedIn, setIsLoggedIn] = useState(false); // 임시 로그인 상태(추후 업데이트예정)
  const [isOpen, setIsOpen] = useState(false);
...
```
이렇게 가독성을 위해서 한줄 띄어서 부탁드립니다!

2024-12-16 15:51 UTC, junghwa1996 commented
![image](https://github.com/user-attachments/assets/183066f9-3540-4353-b94b-beaaed5bbeee)
제가 피그마에도 따로 기재해놨는데 작업하시기전에 이렇게 영역을 나눠보시면 어떻게 쪼개야하는지 쉽게 구분되실거에요!
이건 제가 디스코드 '알려드립니다' 에도 공지로 올려드렸는데 거기서 '리액트 단일 책임 원칙 게시글-[리액트 공식 문서](https://ko.legacy.reactjs.org/docs/thinking-in-react.html)' 꼭 확인해보셔용

2024-12-16 17:23 UTC, solprime commented on components/GNB.tsx
> +
참고하겠습니다

2024-12-16 17:24 UTC, solprime commented on pages/test/GNB/index.tsx
반영했으니 확인 부탁드립니다!

2024-12-16 17:32 UTC, junghwa1996 requested changes
이전 리뷰 반영 확인했습니다!! 
너무 고생많으셨어요..!! 이거 하나만 더 부탁드립니다!
해당 부분 수정완료되면 approve 처리 하겠습니다!

2024-12-16 17:32 UTC, junghwa1996 commented on components/Headers/Headers.tsx
> +  }, []);
이거 모바일 감지 부분 다른 페이지에서도 용이하게 사용될 것 같아서 커스텀 훅으로 빼주실수있나요??

2024-12-16 17:59 UTC, solprime commented on components/Headers/Headers.tsx
> +  }, []);
확인해주세요!

2024-12-16 18:55 UTC, junghwa1996 commented on components/Headers/Headers.tsx
> +  }, []);
확인했습니다!! 수고많으셨어요!!

2024-12-16 18:56 UTC, junghwa1996 approved these changes

2024-12-17 07:31 UTC, haksoo0918 approved these changes
`isMobile` 과 `mo:` 클래스를 같이 사용하셨던데, 어떤 기준으로 두개를 나누어 적용하셨는지 궁금합니다.
소스가 길어서 보는데도 오래 걸렸는데 작업하시는데 힘드셨을것 같아요. 수고하셨습니다. 👍

2024-12-17 07:31 UTC, haksoo0918 commented on public/logo.svg
이 로고 파일은 'public/images/' 안에 들어가야 할 것 같습니다.

2024-12-17 09:46 UTC, solprime commented on public/logo.svg
모바일 환경일때 tailwind css로 변경가능한건 mo: 를 사용하고, 메뉴옵션배열처럼 화면 상태에 따라 달라지는 부분은 isMobile을 사용했습니다. 로고파일 위치는 변경했습니다!

2024-12-18 01:49 UTC, junghwa1996 commented on public/logo.svg
@haksoo0918 학수님 확인해주세요!

2024-12-18 02:06 UTC, merged