#48 heart 컴포넌트
codeitFE11-part3-team7/wikid pull request #52
Opened 2024-12-17 08:12 UTC by junghwa1996

### 이슈 번호

close #48 

### 변경 사항 요약

- 하트 아이콘의 색상 변경을 위해 컴포넌트로 만들었습니다
- 하트 카운트 컴포넌트는 onClick prop가 있을때만 카운트 됨과 동시에 컬러가 변경 됩니다.
- onClick props가 없을 경우에는 클릭 이벤트가 동작하지않고 컬러도 바뀌지않는 정적 컴포넌트로 사용할 수 있습니다.

|props|type|dec|
|------|---|---|
|count|number|하트 카운팅 초기값|
|onClick|function|부모로부터 전달받는 핸들러|

### 테스트 결과
- 평상시
<img width="48" alt="image" src="https://github.com/user-attachments/assets/eeb16e9a-6968-405a-a392-35301df588e2" />

- 클릭 시
<img width="45" alt="image" src="https://github.com/user-attachments/assets/4bda1e96-2681-4aa9-9044-be2f09d4e700" />

2024-12-17 12:18 UTC, haksoo0918 requested changes
간결하게 잘 만들어 주셨습니다. 👍 
div 만 버튼으로 바꿔 주시면 될 것 같습니다.

2024-12-17 12:18 UTC, haksoo0918 commented on components/Heart/Heart.tsx
> +    </div>
div 보다는 button 이 좋을 것 같습니다.

2024-12-17 12:18 UTC, haksoo0918 commented on components/Heart/HeartIcon.tsx
> +    >
svg 사용에 팁을 드리면 svg 에 fill 이나 이런 속성값에 currentColor를 주면 부모의 color값을 따라 갑니다.
```html
<button className="text-green-200"><svg fill="currentColor" ... >...</svg></button>
```

2024-12-17 13:43 UTC, junghwa1996 commented on components/Heart/Heart.tsx
> +    </div>
해당 컴포넌트가 클릭이 되는 형태일때도 있고 클릭이 안되는 정적 컴포넌트일때도 있어서 말씀해주신 의견 반영하여,
onClick props가 있을때는 `button` 태그로, 없을때는 `div`태그로 보이게 하면 좋을 것 같다는 생각이 들었습니다!!
더불어 주신 의견을 반영하던 중 `button` 태그 일때만 `cursor-pointer`가 되면 좋을것같아 해당 부분도 추가하여 수정했습니다!
좀 더 확실한 UI/UX가 된 것 같습니다!!
좋은 의견 너무 감사드립니다 👍🏻

2024-12-17 13:48 UTC, junghwa1996 commented on components/Heart/HeartIcon.tsx
> +    >
해당 컴포넌트에서는 svg 코드가 너무 길어서 별도의 icon 컴포넌트로 분리했는데 코드의 길이가 많지않은 svg를 사용할때, 학수님이 말씀해주신 방식 참고해서 사용하겠습니다!! 감사합니다!! 😊

2024-12-17 14:06 UTC, crazyupinc-design approved these changes
수고하셨습니다 
승인드립니다

2024-12-18 01:36 UTC, junghwa1996 commented
> 간결하게 잘 만들어 주셨습니다. 👍 div 만 버튼으로 바꿔 주시면 될 것 같습니다.

확인되시면 승인 부탁드립니다!

2024-12-18 02:35 UTC, haksoo0918 approved these changes
제가 확인이 늦었네요. 지송합니다.
github 이용이 서툴러서 뭔가 잘못 눌른거 같기도 하고..;;

2024-12-18 02:37 UTC, merged