Feature/#43 게시물 등록하기 페이지
codeitFE11-part3-team7/wikid pull request #64
Opened 2024-12-18 06:54 UTC by haksoo0918

## 이슈 번호

close #43 

## 변경 사항 요약

- 로그인 및 인증 적용 후 다시 테스트 필요함
- 다크토글버튼 왼쪽 아래 고정으로 변경

## 테스트 결과

![image](https://github.com/user-attachments/assets/8b69394c-cda6-4c2c-9879-7cfe37c2c47b)

2024-12-18 07:55 UTC, junghwa1996 requested changes
api 요청 부분 제외하고 리뷰 작성 했습니다!
제목 입력도 잘되고, 에디터도 정상 작동하는 것 같습니다!!
추가로 pages 폴더구조는 아래와 같이 맞춰주실수있을까용?
```
pages/
 addboard/
   index.tsx
```
고생 많으셨어요 !

2024-12-18 07:55 UTC, junghwa1996 commented on pages/addboard.tsx
> +              </h1>
h1태그는 보통 로고에 쓰이지않나요?

> 검색해보니 페이지 본문 타이틀을 작성할때에도 h1 사용이 가능하다고 하네용
> 전 여태 h1태그는 필수로 하나만 써야한다고 알고있었는데 잘못된 내용이었나봐요ㅎ

2024-12-18 07:55 UTC, junghwa1996 commented on pages/addboard.tsx
> +            <header className="my-4 flex items-center justify-between">
margin이 시안과 맞지않는것같아요!
`pc/ta:24px,mo:16px`

2024-12-18 07:55 UTC, junghwa1996 commented on pages/addboard.tsx
> +            </div>
피그마 상에는 타이틀과 등록이 묶여있어서 두개를 묶는 div 태그가 필요할 것 같습니다
그리고 해당 그룹과 에딧의 간격을 주면 좋을 것 같습니다
margin
`pc:33px ta:25px mo:20px`

2024-12-18 07:55 UTC, junghwa1996 commented on pages/addboard.tsx
> +              <p className="mb-2 mt-5 text-16md mo:text-14md">
피그마 시안과 상이합니다!
margin-bottom
`pc/ta: 10px , mo: 16px`

2024-12-18 08:01 UTC, haksoo0918 commented on pages/addboard.tsx
> +              </h1>
그것보다는 h1가 꼭 하나여야 하는건 아니고 구조가 중요하긴 합니다. 구조만 잘 만들면 여러개여도 괜찮습니다.
그렇지만 최근의 방향은 로고는 div 로 하고 페이지 제일 중요한 title 에 들어가는 내용을 h1으로 넣습니다.

2024-12-18 08:03 UTC, haksoo0918 commented on pages/addboard.tsx
> +            <header className="my-4 flex items-center justify-between">
콘테이너 안에 말슴하시는 건가요? 헤더? 65번 라인은 margin-top: 54px 맞는거 같은데요?

2024-12-18 08:06 UTC, haksoo0918 commented on pages/addboard.tsx
> +            </div>
타이틀과 등록일을 말씀하시는 건가요?
html 구조는 개발자 권한이라고 생각하시면 좋을 것 같습니다.
디자이너가 html 구조를 생각하고 디자인을 하지는 않거든요.

2024-12-18 08:08 UTC, junghwa1996 commented on pages/addboard.tsx
> +              </h1>
> 그것보다는 h1가 꼭 하나여야 하는건 아니고 구조가 중요하긴 합니다. 구조만 잘 만들면 여러개여도 괜찮습니다. 그렇지만 최근의 방향은 로고는 div 로 하고 페이지 제일 중요한 title 에 들어가는 내용을 h1으로 넣습니다.

오 대박...새로이 알아가는 것 같습니다! 감사합니다!!
@crazyupinc-design 지이님 저번에 제가 리뷰 남긴거에서 해당 부분 읽어보시고 나중에 리팩토링때 기존에 쓰시던 방식으로 넣으셔도 될것같습니당!

2024-12-18 08:09 UTC, junghwa1996 commented on pages/addboard.tsx
> +            <header className="my-4 flex items-center justify-between">
아고 이게 vscode 내에서는 제가 선택한 한줄이 아닌 윗부분까지 포함돼서 보이네요...ㅠㅠ
제가 본건 66번줄 이었습니다!

2024-12-18 08:15 UTC, junghwa1996 commented on pages/addboard.tsx
> +            </div>
네넵 맞습니다!!
제가 디자인 확인하면서 마진들이 너무 겹쳐있다보니 실 간격이 얼만큼 들어가는지 헷갈려서 드린 얘기였어용
구조는 유지하셔도 될 것 같습니다! 다시 확인해보니 form 태그에서 margin-top으로 간격을 주고있는 것 같더라구요!

2024-12-18 08:36 UTC, haksoo0918 commented
> api 요청 부분 제외하고 리뷰 작성 했습니다! 제목 입력도 잘되고, 에디터도 정상 작동하는 것 같습니다!! 추가로 pages 폴더구조는 아래와 같이 맞춰주실수있을까용?
> 
> ```
> pages/
>  addboard/
>    index.tsx
> ```
> 
> 고생 많으셨어요 !

요거는 이야기 하고픈게 있었는데 내일 미팅때 이야기 하시져. 😄

2024-12-18 08:38 UTC, haksoo0918 reviewed
반응형 전체적으로 다시 꼼꼼히 수정했습니다. 확인 부탁 드립니다.

2024-12-18 08:38 UTC, haksoo0918 commented on pages/addboard.tsx
> +              <p className="mb-2 mt-5 text-16md mo:text-14md">
수정 적용 할께요.

2024-12-18 08:38 UTC, haksoo0918 commented on pages/addboard.tsx
> +            </div>
수치가 안 맞는 것은 확인해서 수정할께요.

2024-12-18 08:38 UTC, haksoo0918 commented on pages/addboard.tsx
> +            <header className="my-4 flex items-center justify-between">
아 헤더 말씀하신 거군요. 확인해서 수정할께여.

2024-12-18 14:42 UTC, junghwaYang approved these changes

2024-12-19 01:56 UTC, crazyupinc-design approved these changes
수고많으셨습니다 승인드립니다

2024-12-19 02:11 UTC, merged