Feature/#74 퀴즈 모달 컴포넌트
codeitFE11-part3-team7/wikid pull request #75
Opened 2024-12-18 10:06 UTC by horororok

## 이슈 번호

close #74

## 변경 사항 요약

 - 구조 변경
 - 공통 버튼 사용
 - 모바일 대응 이벤트 추가
 - 배경, esc 키 관련 props 추가

## Doc

_`   isOpen,
  onClose,
  children,
  closeOnBackgroundClick = false,
  closeOnEsc = true,`_

| **Props** | **Type** | **Description** |
| --------- | -------- | --------------- |
| ` isOpen `      | `  boolean`     | 모달 오픈 여부       |
| ` onClose `      | ` ()=>void `     | 모달 닫기       |
| ` closeOnBackgroundClick `      | ` boolean`     | 배경 클릭시 닫기여부|
| ` closeOnEsc `      | `  boolean`     | esc 눌렀을 시 닫기여부       |

_`  isOpen,
  onClose,
  securityQuestion,
  securityAnswer,
  onQuizComplete,`_

| **Props** | **Type** | **Description** |
| --------- | -------- | --------------- |
| ` isOpen `      | `  boolean`     | 모달 오픈 여부       |
| ` onClose `      | ` ()=>void `     | 모달 닫기       |
| ` securityQuestion`      | ` string `     | 질문       |
| ` securityAnswer`      | `  string`     | 정답       |
| ` onQuizComplete`      | `  ()=>void`     | 퀴즈 완료       |

_`hooks 및 utils 인 경우 input,output을 입력해주세요`_

|            | **prams** | **Type** | **Description** |
| ---------- | --------- | -------- | --------------- |
| **input**  | `  `      | `  `     | 내용 입력       |
| **output** | `  `      | `  `     | 내용 입력       |

## 테스트 결과

_`베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.`_
_`컴포넌트의 경우 스크린샷을 포함해주세요.`_

2024-12-18 14:03 UTC, haksoo0918 reviewed
긴 코드에서 수고하신게 느껴집니다. 👍

2024-12-18 14:03 UTC, haksoo0918 commented on components/Modal/WikiQuizModal.tsx
> +  }, []);
hooks 에 useCheckMobile 있던데 확인해보시고 사용해보셔도 좋을것 같습니다.

2024-12-18 14:03 UTC, haksoo0918 commented on components/Modal/WikiQuizModal.tsx
> +  }, [isOpen]);
98 라인에도 비슷한 코드와 같은 의존성이 있는거 같은데 확인 부탁드립니다.

2024-12-18 14:03 UTC, haksoo0918 commented on components/Modal/WikiQuizModal.tsx
> +      setKeyboardVisible(isKeyboardVisible);
이런 세심한 것까지 👍

2024-12-18 14:52 UTC, junghwa1996 commented
기존에 작업하셨던
`UnsavedChangesModal.tsx`
`ImageUploadModal.tsx`
`DisconnectionModal.tsx`
해당 파일들은 의도적으로 삭제하신건가요?

아예 파일삭제가 됐던데 확인해주세요!

2024-12-19 04:06 UTC, solprime approved these changes
참고해서 사용하겠습니다 감사합니다!

2024-12-19 08:31 UTC, junghwa1996 requested changes
스타일이 전체적으로 시안과 많이 다른것같습니다..!!
아직 스타일 작업 전이셨던걸까요??

그리고 `DisconnectionModal.tsx`와 `UnsavedChangesModal.tsx` 는 들어가는 본문 텍스트만 다르고 나머진 다 동일해서 공통 컴포넌트로 묶을 수 있을 것 같습니다~
호출해서 사용할때 본문 텍스트 string만 받게하면 일관된 디자인으로 사용 가능할 것 같습니다!

기능은 나중에 페이지에 붙히면서 확인해야할것같아서 따로 체크하진않았습니다! (문제없는것같아서용)

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +          <WarningText warning={state.warning} />
요기 에러메세지 나오는쪽보면 너무 딱 붙어있어서 둘사이에 마진을 좀 주면 좋을 것 같습니다~

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +    <p id="warning-message" className="text-xs text-red-500">
text 스타일은 저희가 tailwind로 line-height font-weight font-size 전부 지정해놓은거라 지정스타일로 수정해주세요!

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +            className="mt-4 min-h-[44px] w-full"
버튼과 input의 간격이 시안과 다른것같습니다!

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +      )}
마진과 폰트 컬러가 다른것같습니다! 그리고 텍스트 스타일은 커스텀 클래스 사용해주세요!
그리고 어차피 p태그 둘이 폰트 스타일이 같다면 부모요소에 텍스트 스타일 주셔도 될것같습니다

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +            </div>
여기도 커스텀 폰트 스타일 사용해주세요~
그리고 스타일이 같으면 부모요소에 스타일 추가해주세용

mt 간격이 시안과 상이 합니당

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +            className={`w-full text-left text-lg font-bold ${
지정된 커스텀 텍스트 스타일 사용해주세요!

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +              keyboardVisible ? 'mt-1' : 'mt-4'
여기 모바일과 pc로 잘 구분해주셨는데 pc일때 여백이 시안과 다른것같아요~

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/UnsavedChangesModal.tsx
>          <p className="text-sm">작성하신 모든 내용이 사라집니다.</p>
여기도 지정 폰트 스타일로 수정해주시고 작성하진~ 부분은 text 컬러가 상이합니당

그리고 해당 코드 아래에 button이 컴포넌트가 아니네용 컴포넌트로 사용해주세요!
본문과 버튼 간격도 수정해주세요!

2024-12-19 08:31 UTC, junghwa1996 commented on components/Modal/ImageUploadModal.tsx
여기 이미지 타이틀 가운데 정렬해주시고 텍스트 스타일은 지정된 스타일 사용해주세요~
그리고 삽입하기 버튼 디자인이 달라용

2024-12-20 11:21 UTC, junghwa1996 commented
> 스타일이 전체적으로 시안과 많이 다른것같습니다..!! 아직 스타일 작업 전이셨던걸까요??
> 
> 그리고 `DisconnectionModal.tsx`와 `UnsavedChangesModal.tsx` 는 들어가는 본문 텍스트만 다르고 나머진 다 동일해서 공통 컴포넌트로 묶을 수 있을 것 같습니다~ 호출해서 사용할때 본문 텍스트 string만 받게하면 일관된 디자인으로 사용 가능할 것 같습니다!
> 
> 기능은 나중에 페이지에 붙히면서 확인해야할것같아서 따로 체크하진않았습니다! (문제없는것같아서용)

해당 스타일 작업 issue #109 PR #110 과 이어짐
PR 머지 완료 시 approve 예정

2024-12-20 13:42 UTC, junghwa1996 commented on components/Modal/WikiQuizModal.tsx
> +  }, [isOpen]);
@horororok 이거 확인 됐나요 태훈님?

2024-12-20 13:44 UTC, horororok commented on components/Modal/WikiQuizModal.tsx
> +  }, [isOpen]);
@junghwa1996 네 중복 코드 삭제 했습니다

2024-12-20 15:30 UTC, junghwa1996 approved these changes

2024-12-20 15:30 UTC, merged